@startuml
'https://plantuml.com/use-case-diagram

left to right direction

rectangle Programa {
    usecase "Modificar un mapa" as mod_mapa
    usecase "Visualizar un mapa" as viz_mapa
    usecase "Cargar un polígono" as cargar_pol
    usecase "Crear un polígono" as crear_pol
    usecase "Exportar información \nde un mapa" as export_mapa
    usecase "Visualizar mapa en \ndos dimensiones" as viz_mapa_2d
    usecase "Visualizar mapa en \ntres dimensiones" as viz_mapa_3d
}

Usuario -> viz_mapa
Usuario -> mod_mapa

crear_pol <.. viz_mapa : <<incluye>>
mod_mapa <.. crear_pol : <<incluye>>
mod_mapa <. viz_mapa : <<incluye>>
mod_mapa <.. export_mapa : <<extiende>> \n Si usuario desea guardar \n cambios en el mapa
crear_pol <. cargar_pol : <<extiende>> \n Si usuario desea cargar \npolígono almacenado en un archivo

viz_mapa_2d --|> viz_mapa
viz_mapa_3d --|> viz_mapa

@enduml