@startuml

' Variable definition
!$file = "(F,#ff75ff) File"

' Configuration definition
title Class Diagram For Reliefe Creator
set namespaceSeparator .

' Package hierarchy
package src {
    package engine {
        package render {}
        package data {}
        package controller {}
        package GUI {
            package frames {}
        }
        package scene {
            package model {
                package transformations {}
            }
        }
    }
    package input {}
    package program {}
}


' Classes definition
class src.engine.GUI.GUIManager{
    - __implementation: GlfwRenderer
    - __glfw_window: GLFWWindow
    - __component_list: list
    - __io: IMGUI.io
    - __font: IMGUI.font
    - __scene: Scene
    - __engine: Engine

    {static} + get_frames(gui_manager) : list
    + add_frames(component_list)
    + add_zoom()
    + are_frame_fixed()
    + change_color_file(path_color_file)
    + change_quality(quality)
    + draw_frames()
    + fix_frames_position(value)
    + get_active_tool(): str
    + get_cpt_file(): str
    + get_left_frame_width(): int
    + get_main_menu_bar_height(): int
    + get_map_position(): list
    + get_quality(): int
    + get_view_mode(): str
    + get_window_height(): int
    + get_window_width(): int
    + get_zoom_level(): float
    + initialize(window, mode)
    + is_program_loading(): boolean
    + less_zoom()
    + process_input()
    + refresh_scene_with_model_2d(path_color_file, path_model, model_id)
    + reload_models()
    + render()
    + set_polygon_mode(polygon_mode)
    + set_loading_message(new_msg)
}

class src.engine.settings  {
    {static} + CLEAR_COLOR: list
    {static} + fix_frames(fix_frames): boolean
    {static} + FIXEX_FRAMES: boolean
    {static} + FLOAT_BYTES: int
    {static} + FONT_SIZE: int
    {static} + HEIGHT: int
    {static} + LEFT_FRAME_WIDTH: int
    {static} + MAIN_MENU_BAR_HEIGHT: int
    {static} + QUALITY: int
    {static} + SCENE_BEGIN_X: int
    {static} + SCENE_BEGIN_Y: int
    {static} + SCENE_WIDTH_X: int
    {static} + SCENE_HEIGHT_Y: int
    {static} + VIEW_MODE: str
    {static} + TOP_FRAME_HEIGHT: int
    {static} + WIDTH: int
    {static} + MIN_WIDTH: int
    {static} + MIN_HEIGHT: int
    {static} + MAX_WIDTH: int
    {static} + MAX_HEIGHT: int
    {static} + update_scene_values()
}

class src.engine.scene.model.transformations.transformations <<$file>> {
    + identity() : array
    + uniformScale(s) : array
    + scale(sx,sy,sz) : array
    + rotationX(theta) : array
    + rotationY(theta) : array
    + rotationZ(theta) : array
    + rotationA(theta, axis) : array
    + translate(tx, ty, tz) : array
    + shearing(xy, yx, xz, zx, yz, zy) : array
    + matmul(mats) : array
    + frustum(left, right, bottom, top, near, far) : array
    + perspective(fovy, aspect, near, far) : array
    + ortho(left, right, bottom, top, near, far) : array
    + lookAt(eye, at, up) : array
}


class src.engine.scene.model.Model {
    + vao: int
    + vbo: int
    + cbo: int
    + ebo: int
    + shader_program: compiled_shader
    + position: numpy.array[3]
    + rotation: numpy.array[3]
    + indices_size: int
    + draw_mode: GL_DRAW_MODE
    + polygon_mode: GL_POLYGON_MODE
    + update_uniform_values: boolean
    + id: str
    + scene: Scene

    ~ _update_uniforms()
    + set_color_file(color_file)
    + set_shaders(vertex_shader, fragment_shader)
    + set_vertices(vertex)
    + set_indices(indices)
    + draw()
}

class src.engine.render.Render {
    + __window : GLFWWindow
    + __gui : GUIManager
    + __engine : Engine
    + init(window_name)
    + on_loop(on_frame_task)
}

class src.input.NetCDF <<$file>> {
    + read_info(filename) -> array, array, array
}

class src.engine.data.decimation <<$file>>{
    + simple_decimation(x, y, z, n_rows, n_cols): array, array, array
}

class src.utils <<$file>>{
    + LOG_LEVEL : int
    + LOG_FILE_LEVEL : int
    + interpolate(value, value_min, value_max, target_min,target_max) : float
    + get_logger(log_level, log_file_level, module, directory) : logger
}

class src.engine.scene.model.Map2DModel{
    - __x : array
    - __y : array
    - __z : array
    - __color_file : str
    - __colors : array
    - __height_limit : array
    - __vertices : list
    - __indices : list
    - __height : list
    - __max_height : float
    - __min_height : float
    - __projection : list
    - __left_coordinate : int
    - __right_coordinate : int
    - __top_coordinate : int
    - __bottom_coordinate : int
    + hbo : int

    - __print_vertices()
    - __print_indices()
    - __set_height_buffer()
    - __generate_vertices_list(x, y, z, z_value): list
    - __get_vertex_index(x_pos, y_pos): int
    - __get_index_closest_value(list_to_evaluate, value): int
    - __generate_index_list(step_x, step_y, left_coordinate, right_coordinate, top_coordinate, bottom_coordinate): list
    - __is_triangle_inside_zone(index_triangle, left_coordinate, right_coordinate, top_coordinate, bottom_coordinate): boolean
    - __delete_triangles_inside_zone(left_coordinate, right_coordinate, top_coordinate, bottom_coordinate)
    ~ _update_uniforms()
    + recalculate_vertices_from_grid_async(quality, then)
    + calculate_projection_matrix(scene_data, zoom_level)
    + set_color_file(filename)
    + set_vertices_from_grid_async(x,y,z,quality, then)

}

class src.input.CTP <<$file>> {
    + read_file(filename: str) : dict
}

class src.engine.scene.model.Map3DModel{

}

'class src.main <<$file>> {
'
'}

class src.engine.GUI.frames.Frame {
    ~ _position: list
    ~ _GUI_manager: GUIManager

    + change_position(new_position)
    + get_position(): list
    + render()
}

class src.engine.GUI.frames.MainMenuBar {
    + render()
}

class src.engine.GUI.frames.Tools {
    - double_button_margin_width: int
    - button_margin_width: int
    + render()
}

class src.engine.GUI.frames.Debug {
    - __height: int
    + render()
}

class src.engine.GUI.frames.Loading {
    - __loading_message: str
    - __windows_width: int
    - __windows_height: int
    + render()
    + set_loading_message(new_msg)
}

class src.engine.GUI.frames.TestWindow {
    + render()
}

class src.engine.controller.Controller {
    - __render : Render
    - __scene : Scene
    - __engine : Engine
    + init(render)
    + get_on_key_callback()
    + get_resize_callback()
}

class src.engine.scene.Scene {
    - __model_list : list
    - __engine : Engine
    - __width_viewport: int
    - __height_viewport: int
    - __should_execute_then_reload: int
    + add_model(model)
    + draw()
    + initialize(engine)
    + refresh_with_model_2d(path_color_file, path_model, model_id)
    + reload_models_async(then)
    + remove_all_models()
    + remove_model(id_model)
    + set_loading_message(new_msg)
    + set_polygon_mode(polygon_mode)
    + update_models_colors()
    + update_models_projection_matrix()
    + update_viewport()
    + update_viewport_variables()
}

class src.engine.Engine {
    + controller: Controller
    + gui_manager: GUIManager
    + render: Render
    + scene: Scene
    + window: GLFWWindow
    - __pending_task_list: list
    + add_zoom()
    + are_frames_fixed(): boolean
    + change_color_file(path_color_file)
    + change_height_window(height)
    + change_quality(quality)
    + change_width_window(width)
    + fix_frames()
    + get_active_tool(): str
    + get_clear_color(): list
    + get_CPT_file()
    + get_cpt_file(): str
    + get_float_bytes()
    + get_float_bytes(): int
    + get_font_size(): int
    + get_gui_setting_data(): dict
    + get_map_position(): list
    + get_quality(): int
    + get_scene_setting_data(): dict
    + get_scene_setting_data(): dict
    + get_view_mode(): str
    + get_window_setting_data(): dict
    + get_zoom_level(): float
    + initialize(engine)
    + is_program_loading(): boolean
    + less_zoom()
    + refresh_with_model_2d_async(path_color_file, path_model, model_id, then)
    + reload_models()
    + reset_zoom_level()
    + run()
    + set_loading_message(new_msg)
    + set_parallel_task(parallel_task, then)
    + set_task_for_next_frame(task)
    + set_task_with_loading_frame(task)
    + set_thread_task(parallel_task, then)
    + update_pending_tasks()
    + update_scene_values()
    + update_threads()

}

class src.program.Program {

    - __engine: Engine
    - __CPT_file: str
    - __model_id: str
    - __zoom_level: float
    - __map_position: list
    - __active_tool: str
    - __loading: boolean

    + add_zoom()
    + get_active_tool(): str
    + get_cpt_file(): str
    + get_map_position(): list
    + initialize(program)
    + is_loading(): boolean
    + less_zoom()
    + reset_zoom_level()
    + run()
    + set_active_tool(new_tool)
    + set_cpt_file(new_file)
    + set_loading(is_loading)
    + set_model_id(new_model_id)
}

' herency
src.engine.scene.model.Map2DModel -u-|> src.engine.scene.model.Model
src.engine.scene.model.Map3DModel -u-|> src.engine.scene.model.Model

src.engine.GUI.frames.MainMenuBar -u-|> src.engine.GUI.frames.Frame
src.engine.GUI.frames.Tools -u-|> src.engine.GUI.frames.Frame
src.engine.GUI.frames.TestWindow -u-|> src.engine.GUI.frames.Frame
src.engine.GUI.frames.Debug -u-|> src.engine.GUI.frames.Frame
src.engine.GUI.frames.Loading -u-|> src.engine.GUI.frames.Frame

' uses
src.engine.scene.model.Map2DModel -u.> src.engine.data.decimation
src.engine.scene.model.Map2DModel -u.> src.engine.scene.model.transformations.transformations
src.engine.scene.model.Map2DModel -u.> src.input.CTP

src.engine.Engine <-d.> src.engine.render.Render
src.engine.Engine <-d.> src.engine.GUI.GUIManager
src.engine.Engine <-d.> src.engine.controller.Controller
src.engine.Engine <-d.> src.engine.scene.Scene
src.engine.Engine -u.> src.engine.settings
src.engine.Engine <-l.> src.program.Program

src.engine.GUI.frames.Frame <-u.> src.engine.GUI.GUIManager

src.engine.scene.Scene .> src.engine.scene.model.Model
src.engine.scene.Scene -u.> src.input.NetCDF
@enduml