@startuml
'https://plantuml.com/class-diagram
!$file = "(F,#ff75ff) File"

title "Class diagram of the engine package"

left to right direction
hide members

note top of engine : Dependencies of subpackages are not shown in the diagram.

' Include main package to show
!includesub packages/src.engine.puml!INTERNAL

' Generate packages for external dependencies to show them more organized
package src <<External Dependencies>> {
    package program {
        class Program
    }
    package output {
        class ShapefileExporter
        class NetcdfExporter
    }
    package input {
        class ShapefileImporter
    }
}

' Include external dependencies
!includesub packages/src.engine.puml!EXTERNAL

@enduml