@startuml
'https://plantuml.com/class-diagram

!$file = "(F,#ff75ff) File"



    package engine {
        class Engine
        class Settings
        package scene {
            class Scene
        }
        package render {
            class Render
        }
        package controller {
            class Controller
        }
        package data {
            class decimation
        }
        package GUI {
            class GUIManager
        }
    }

package src <<External Dependencies>> {

    package program {
        class Program
    }

    package output {
        class ShapefileExporter
    }

}

!include classes/Engine.puml
!include classes/Render.puml
!include classes/Settings.puml
!include classes/Controller.puml
!include file_modules/decimation.puml
'!include classes/GUIManager.puml

Engine o--o Scene
Engine o--o Controller
Engine o--o Render
Engine o--o GUIManager
Engine o--o Program

Engine -u.> Settings

Engine o-- ShapefileExporter

@enduml