@startuml
'https://plantuml.com/class-diagram

title Class diagram for the GUI package (Updated March 4 of 2021)

!includesub packages/src.engine.gui.puml!INTERNAL

package src {
    !includesub packages/src.error.puml!INTERNAL

    package error {
        hide members
    }

    package engine {
        hide members
        class Engine
    }
}

!includesub packages/src.engine.gui.puml!EXTERNAL

!include classes/PolygonInformation.puml
!include classes/ReliefTools.puml
!include classes/PolygonFolder.puml
!include classes/GUIManager.puml
!include classes/Icon.puml
!include classes/Frame.puml
!include classes/MainMenuBar.puml
!include classes/Debug.puml
!include classes/Loading.puml
!include classes/TextModal.puml
!include classes/TestWindow.puml
!include classes/Tools.puml
!include classes/PolygonFolderManager.puml


@enduml