@startuml
'https://plantuml.com/class-diagram

title Class diagram for the GUI package (Updated March 4 of 2021)

package GUI{
    class GUIManager
    class Icon
    class PolygonFolder
    class PolygonFolderManager

    package frames {

        package tools{
            class Tools
            class ReliefTools
        }
        class Frame
        class MainMenuBar
        class Debug
        class Loading
        class TestWindow
        class TextModal
        class PolygonInformation
    }
}

package src <<External Dependencies>> {

    package engine {
        class Engine
    }

    package error {
        class NotEnoughPointsError

        class PolygonFolderNotFoundError
    }

}

!include classes/PolygonInformation.puml
!include classes/ReliefTools.puml
!include classes/PolygonFolder.puml
!include classes/GUIManager.puml
!include classes/Icon.puml
!include classes/Frame.puml
!include classes/MainMenuBar.puml
!include classes/Debug.puml
!include classes/Loading.puml
!include classes/TextModal.puml
!include classes/TestWindow.puml
!include classes/Tools.puml
!include classes/PolygonFolderManager.puml

Debug -u-|> Frame
Loading -u-|> Frame
MainMenuBar -u-|> Frame
TestWindow -u-|> Frame
TextModal -u-|> Frame
Tools -u-|> Frame
PolygonInformation -u-|> Frame

PolygonFolderManager o-- PolygonFolder

GUIManager o-- PolygonFolderManager
GUIManager o-- Icon
GUIManager o--o Frame
GUIManager o--o Engine

Tools *-> ReliefTools

PolygonFolderManager .> PolygonFolderNotFoundError
Tools .> NotEnoughPointsError

@enduml