@startuml
'https://plantuml.com/class-diagram

!$file = "(F,#ff75ff) File"

package src {
    package input {
        hide members
        !include file_modules/CTP.puml
        !include file_modules/NetCDF.puml
    }
    package error {
        hide members
        class NonExistentPolygonError
    }
    package engine {
        hide members
        class Engine
        package data{
        hide members
            !include file_modules/decimation.puml
        }
    }
}

!includesub packages/src.engine.scene.puml!INTERNAL
!includesub packages/src.engine.scene.puml!EXTERNAL
!includesub packages/src.engine.scene.model.puml!EXTERNAL

!include classes/DashedLines.puml
!include classes/Lines.puml
!include classes/Map2DModel.puml
!include classes/Model.puml
!include classes/Points.puml
!include classes/Polygon.puml
!include classes/Scene.puml

@enduml