@startuml
'https://plantuml.com/class-diagram

title Class diagram for the src package (updated March 4 of 2021)

!includesub packages/src.puml!INTERNAL

hide members

!include file_modules/CTP.puml
!include file_modules/NetCDF.puml
!include file_modules/utils.puml
!include file_modules/parser.puml

!include classes/ShapefileExporter.puml
!include classes/Program.puml

Program o--o Engine
Engine o-- ShapefileExporter

@enduml