@startuml
!$file = "(F,#ff75ff) File"
class src.utils <<$file>> {
    + LONGITUDE_KEYS: list
    + LATITUDE_KEYS: list
    + HEIGHT_KEYS: list

    + LOG_TO_FILE: boolean
    + LOG_TO_CONSOLE: boolean
    + LOG_LEVEL: int
    + LOG_FILE_LEVEL: int
    + LOG_ONLY_LISTED_MODULES: boolean
    + LOG_LIST_MODULES: list

    + dict_to_json(dictionary, filename): None
    + dict_to_serializable_dict(dictionary): dict
    + get_logger(log_level, log_file_level, module, directory) : logger
    + is_clockwise(points): boolean
    + is_numeric(value) : boolean
    + json_to_dict(json_filename): dict
    + list_to_serializable_list(list_obj): list
}
@enduml