@startuml

class Camera{
        - __camera_pos: array
        - __look_: array
        - __norm: array
        - __radius: float
        - __phi: float
        - __rho: float

        + get_view_matrix(): array
        + reset_values()
        + make_radius_bigger(change_value)
        + make_radius_smaller(change_value)
        - __spherical_to_cartesian(radius, phi, rho): array
}

@enduml