@startuml
'https://plantuml.com/class-diagram

class ConfirmationModal {

        - __yes_func: function
        - __no_func: function
        - __button_width: int
        - __modal_title: str
        - __msg: str

        + post_render()
        + set_confirmation_text(modal_title, msg, yes_func, no_func)

}

@enduml