@startuml
class Controller {
    - __engine: Engine
    - __mouse_old_pos: tuple
    - __render: Render
    - __scene: Scene
    - __is_left_alt_pressed: boolean
    - __is_left_ctrl_pressed: boolean
    - __is_left_mouse_being_pressed: boolean

    - __change_color_file_with_dialog()
    - __is_inside_scene(mouse_x_pos, mouse_y_pos): boolean
    - __load_netcdf_file_with_dialog()
    - __load_shapefile_file_with_dialog()
    - __set_mouse_pos(new_x, new_y)
    + enable_glfw_keyboard_callback()
    + disable_glfw_keyboard_callback
    + get_cursor_position_callback(): function
    + get_mouse_button_callback(): function
    + get_on_key_callback(): function
    + get_resize_callback(): function
    + get_mouse_scroll_callback(): function
    + init(render)
}
@enduml