@startuml
class Engine {
    + controller: Controller
    + gui_manager: GUIManager
    + render: Render
    + scene: Scene
    + window: GLFWWindow
    - __pending_task_list: list
    + add_new_vertex_to_active_polygon_using_window_coords(position_x, position_y)
    + add_zoom()
    + are_frames_fixed(): boolean
    + export_model_as_netcdf(model_id)
    + calculate_max_min_height(model_id, polygon_id): tuple
    + change_color_file_with_dialog()
    + change_color_of_polygon(polygon_id, color)
    + change_dot_color_of_polygon(polygon_id,  color)
    + change_height_window(height)
    + change_quality(quality)
    + change_width_window(width)
    + create_new_polygon(): str
    + delete_parameter_from_polygon(polygon_id, key)
    + delete_polygon_by_id(polygon_id)
    + export_polygon_list_id(polygon_id_list, filename)
    + export_polygon_with_id(polygon_id)
    + fix_frames()
    + get_active_model_id()
    + get_active_polygon_id(): str
    + get_active_tool(): str
    + get_clear_color(): list
    + get_cpt_file(): str
    + get_float_bytes()
    + get_float_bytes(): int
    + get_font_size(): int
    + get_gui_key_callback(): function
    + get_gui_scroll_callback(): function
    + get_gui_setting_data(): dict
    + get_map_position(): list
    + get_parameters_from_polygon(polygon_id): list
    + get_polygon_id_list(): list
    + get_polygon_name(polygon_id): str
    + get_quality(): int
    + get_render_settings()
    + get_scene_setting_data(): dict
    + get_tool_title_font_size(): int
    + get_view_mode(): str
    + get_window_setting_data(): dict
    + get_zoom_level(): float
    + initialize(engine)
    + is_mouse_hovering_frame()
    + is_polygon_planar(polygon_id)
    + is_program_loading(): boolean
    + less_zoom()
    + load_netcdf_file_with_dialog()
    + load_polygon_from_shapefile(filename)
    + load_shapefile_file_with_dialog()
    + move_scene(x_movement, y_movement)
    + optimize_gpu_memory()
    + refresh_with_model_2d_async(path_color_file, path_model, model_id, then)
    + reload_models()
    + reset_zoom_level()
    + run()
    + set_active_polygon(polygon_id)
    + set_active_tool(tool)
    + set_loading_message(new_msg)
    + set_map_position(new_position)
    + set_modal_text(title_modal, msg)
    + set_models_polygon_mode(polygon_mode)
    + set_new_parameter_to_polygon(polygon_id, key, value)
    + set_polygon_name(polygon_id, new_name)
    + set_program_loading(new_state)
    + set_task_for_next_frame(task)
    + set_task_with_loading_frame(task)
    + set_process_task(parallel_task, then_task, parallel_task_args, then_task_args)
    + set_thread_task(parallel_task, then, parallel_task_args, then_task_args)
    + transform_points_using_linear_transformation(polygon_id, model_id, min_height, max_height)
    + undo_action()
    + update_pending_tasks()
    + update_scene_models_colors()
    + update_scene_values()
    + update_scene_viewport()
    + update_threads()
}

@enduml