@startuml
class Engine {
    + controller: Controller
    + gui_manager: GUIManager
    + render: Render
    + scene: Scene
    + window: GLFWWindow
    - __thread_manager: ThreadManager
    - __process_manager: ProcessManager
    - __task_manager: TaskManager

    - __initialize_components()
    + add_new_vertex_to_active_polygon_using_window_coords(position_x, position_y)
    + add_zoom()
    + are_frames_fixed(): boolean
    + calculate_max_min_height(model_id, polygon_id): tuple
    + change_3D_model_height_unit(model_id, measure_unit)
    + change_3D_model_position_unit(model_id, measure_unit)
    + change_camera_elevation(angle)
    + change_camera_xy_angle(angle)
    + change_color_file_with_dialog()
    + change_color_of_polygon(polygon_id, color)
    + change_current_3D_model_normalization_factor(new_factor)
    + change_dot_color_of_polygon(polygon_id,  color)
    + change_height_window(height)
    + change_model_draw_priority(model_id, new_position)
    + change_polygon_draw_order(polygon_id, new_position)
    + change_quality(quality)
    + change_width_window(width)
    + create_model_from_existent(base_model_id, second_model_id, new_model_name)
    + create_new_polygon(): str
    + create_polygon_from_file(filename)
    + create_preview_interpolation_area(distance)
    + exit()
    + export_model_as_netcdf(model_id)
    + export_polygon_list_id(polygon_id_list, filename)
    + export_polygon_with_id(polygon_id)
    + fix_frames()
    + get_3d_model_list(): List[str]
    + get_active_model_id()
    + get_active_polygon_id(): str
    + get_active_tool(): str
    + get_camera_settings(): dict
    + get_clear_color(): list
    + get_controller_key_callback_state(): boolean
    + get_cpt_file(): str
    + get_extra_reload_proportion_setting(): float
    + get_float_bytes()
    + get_float_bytes(): int
    + get_font_size(): int
    + get_gui_key_callback(): function
    + get_gui_scroll_callback(): function
    + get_gui_setting_data(): dict
    + get_height_normalization_factor_of_active_3D_model(): float
    + get_map_coordinates_from_window_coordinates(x_coordinate, y_coordinate): (float, float)
    + get_map_height_on_coordinates(x_coordinate, y_coordinate): float
    + get_map_position(): list
    + get_model_information(): dict
    + get_model_list(): List[str]
    + get_parameters_from_polygon(polygon_id): list
    + get_polygon_id_list(): list
    + get_polygon_name(polygon_id): str
    + get_program_view_mode(): str
    + get_quality(): int
    + get_render_settings()
    + get_scene_setting_data(): dict
    + get_tool_sub_title_font_size(): int
    + get_tool_title_font_size(): int
    + get_window_setting_data(): dict
    + get_zoom_level(): float
    + interpolate_points(interpolation)
    + is_mouse_hovering_frame()
    + is_polygon_planar(polygon_id)
    + is_program_debug_mode(): boolean
    + is_program_loading(): boolean
    + less_zoom()
    + load_netcdf_file_with_dialog()
    + load_shapefile_file_with_dialog()
    + modify_camera_radius(distance)
    + move_camera_position(movement)
    + move_scene(x_movement, y_movement)
    + optimize_gpu_memory()
    + refresh_with_model_2d_async(path_color_file, path_model, model_id, then)
    + reload_models()
    + remove_interpolation_preview(polygon_id)
    + remove_model(model_id)
    + remove_parameter_from_polygon(polygon_id, key)
    + remove_polygon_by_id(polygon_id)
    + reset_camera_values()
    + reset_map_position()
    + reset_zoom_level()
    + run()
    + set_active_polygon(polygon_id)
    + set_active_tool(tool)
    + set_controller_key_callback(new_state)
    + set_loading_message(new_msg)
    + set_modal_text(title_modal, msg)
    + set_models_polygon_mode(polygon_mode)
    + set_new_parameter_to_polygon(polygon_id, key, value)
    + set_polygon_name(polygon_id, new_name)
    + set_process_task(parallel_task, then_task, parallel_task_args, then_task_args)
    + set_program_loading(new_state)
    + set_program_view_mode(mode)
    + set_task_for_next_frame(task)
    + set_task_with_loading_frame(task)
    + set_thread_task(parallel_task, then, parallel_task_args, then_task_args)
    + should_use_threads(value)
    + transform_points(transformation)
    + undo_action()
    + update_current_3D_model()
    + update_scene_models_colors()
    + update_scene_values()
    + update_scene_viewport()
}

@enduml