@startuml
'https://plantuml.com/class-diagram

class Frame {
    ~ _position: list
    ~ _GUI_manager: GUIManager

    + add_new_polygon(polygon_id)
    + change_position(new_position)
    + get_position(): list
    + render()
    + post_render()
}
@enduml