@startuml
class Map3DModel {
    + hbo: int
    - __color_file: str
    - __colors: list
    - __height_array: array
    - __height_limit: list
    - __model: array
    - __height_exaggeration_factor: float
    - __quality: int

    - __get_conversion_factor(): float
    - __set_height_buffer()
    ~ _update_uniforms()
    + change_height_measure_unit(new_measure_unit)
    + change_height_normalization_factor(new_value)
    + change_vertices_measure_unit(new_measure_unit)
    + draw()
    + get_normalization_height_factor(): float
    + set_color_file(filename)
    + update_values_from_2D_model()

}
@enduml