@startuml
class Map3DModel {
    + hbo: int
    - __color_file: str
    - __colors: list
    - __height_array: array
    - __height_limit: list
    - __max_height: float
    - __min_height: float
    - __model: array
    - __normalize_height_limits_by: int
    - __projection: array
    - __quality: int
    - __view: array

    ~ _update_uniforms()
    + set_color_file(filename)
    + calculate_projection_matrix()
    + update_values_from_2D_model()
    + change_height_normalization_factor(new_value)
    + get_normalization_height_factor(): float
    + draw()
    + change_height_measure_unit(new_measure_unit)
    + change_vertices_measure_unit(new_measure_unit)
    - __set_height_buffer()

}
@enduml