@startuml
'https://plantuml.com/class-diagram

class NanConvolutionMapTransformation {
    - __nan_percentage_limit: float
    - __kernel_diameter: int
    - __model_vertices: array

    + initialize(scene)
    + apply(): array
}

@enduml