@startuml

class Plane{
    - __plane_color: tuple
    - __vertex_shader_file: str
    - __fragment_shader_file: str
    - __vertices_list: array
    - __indices_list: array

    + set_triangles(vertices)
    + set_plane_color(new_color)
    + draw()
}

@enduml