@startuml

class PolygonTools{

    - __button_margin_width: int
    - __color_pick_should_open: boolean
    - __color_pick_window_size_x: int
    - __color_pick_window_size_y: int
    - __color_selected_default: int, int, int, int
    - __color_selected_dict: dict
    - __dot_color_selected_default: int, int, int, int
    - __GUI_manager: GUIManager
    - __hide_dots_default: boolean
    - __input_text_value: str
    - __open_rename_folder_popup: boolean
    - __opened_action_popup_dict: dict
    - __rename_folder_input_text_value: str
    - __rename_padding_x: int
    - __rename_size_x: int
    - __rename_size_y: int
    - __tool_before_pop_up: str

    - __change_folder_selectable(polygon_id): boolean
    - __color_button(polygon_id)
    - __create_new_polygon(folder_id)
    - __delete_selectable(active_polygon, polygon_id): boolean
    - __export_selectable(polygon_id): boolean
    - __folder_popup_menu(folder_id)
    - __generate_polygon_list()
    - __polygon_action_logic(active_polygon, polygon_id)
    - __rename_polygon_selectable(polygon_id): boolean
    - __show_polygon_tools(left_frame_width)
    + add_new_polygon(polygon_id)
    + render()
}
@enduml