@startuml
class ReliefTools {
    - __transformation_options: list[str]
    - __selected_transformation_option: int
    - __gui_manager: GUIManager
    - __max_height_value: float
    - __min_height_value: float
    - __polygon_data: dict
    - __filter_options: list
    - __filters: list
    - __max_min_data_values: list[float]
    - __return_array_values: list[float, None]

    - __get_filters_dictionary_list(): list
    + filter_menu()
    + render()
    + transformation_menu(self, active_model_id, active_polygon_id)
}

@enduml