@startuml
class Render {
    - __window: GLFWWindow
    - __gui: GUIManager
    - __engine: Engine
    - __previous_time: float
    - __frame_count: int
    - __current_time: float
    - __show_framerate: boolean

    + init(window_name)
    + enable_depth_buffer(enable_buffer)
    + on_loop(on_frame_task)
}
@enduml