@startuml
class Tools {
    - __button_margin_width: int
    - __double_button_margin_width: int
    - __slide_bar_quality: int
    - __tools_names_dict: dict
    - __relief_tools: ReliefTools
    - __polygon_tools: PolygonTools

    + add_new_polygon(polygon_id)
    + render()
    - __show_active_tool()
    - __show_editing_tools(left_frame_width)
    - __show_visualization_tools(left_frame_width)
}

@enduml