@startuml
'https://plantuml.com/class-diagram

class TransformationHelper {

    - __generate_mask(points, polygon_points)
    - __delete_z_axis(list_of_points)
    - __get_bounding_box_indexes(points_array, polygon): list
    - __interpolate_nan(array_2d, interpolation_type): array
    + get_inside_polygon_triangulation(polygon_points, z_value): list
    + get_max_min_inside_polygon(points, polygon_points, height): tuple
    + interpolate_points_external_to_polygon(points, polygon_points, heights, distance): array
    + modify_points_inside_polygon_linear(points, height, polygon_points, new_max_height, new_min_height)
    + get_interpolation_zone_triangulation(internal_polygon_points, external_polygon_points, distance, z_value): list
    + apply_smoothing_over_area(internal_polygon_points, external_polygon_points, points_array, heights): array
}

@enduml